[build]
  command = "cp next.config.js.netlify next.config.js && npm run build:netlify"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optimize for Netlify
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --production=false"
  NEXT_TELEMETRY_DISABLED = "1"

# Redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 