[build]
  command = "NEXT_PUBLIC_FIREBASE_API_KEY=dummy-key-for-build npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 